Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 65

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/GuardClause:
  Enabled: false